# Generated by Django 5.1.6 on 2025-02-19 14:14

import cloudinary_storage.storage
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                quality=75,
                scale=None,
                size=[300, 300],
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to="profiles/",
            ),
        ),
    ]
