# Generated by Django 5.1.6 on 2025-02-15 08:53

import cloudinary_storage.storage
import django.db.models.deletion
import django_resized.forms
import djrichtextfield.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("summary", models.CharField(max_length=500)),
                ("content", djrichtextfield.models.RichTextField(max_length=20000)),
                (
                    "featured_image",
                    django_resized.forms.ResizedImageField(
                        crop=None,
                        force_format="WEBP",
                        keep_meta=True,
                        quality=75,
                        scale=None,
                        size=[800, None],
                        storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                        upload_to="gardening_blog/",
                    ),
                ),
                ("image_alt", models.CharField(max_length=150)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("tips", "Gardening Tips"),
                            ("organic", "Organic Gardening"),
                            ("seasonal", "Seasonal Gardening"),
                            ("composting", "Composting"),
                            ("pest_control", "Pest Control"),
                            ("plant_care", "Plant Care"),
                            ("harvesting", "Harvesting"),
                            ("edible_leaves", "Edible Leaves"),
                            ("flowers", "Flowers"),
                            ("fruits", "Fruits"),
                            ("root_tubers", "Root & Tubers"),
                            ("bulbs_stems", "Bulbs & Stems"),
                            ("vegetable_history", "History of Vegetables"),
                        ],
                        default="tips",
                        max_length=50,
                    ),
                ),
                ("published_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_author",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-published_date"],
            },
        ),
    ]
