# Generated by Django 5.1.6 on 2025-02-11 10:03

import cloudinary_storage.storage
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardening_blog', '0003_alter_blogpost_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[800, None], storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='gardening_blog/'),
        ),
    ]
